# Generated by Django 3.1.4 on 2021-01-06 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spares',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine', models.CharField(max_length=100, verbose_name='machine')),
                ('code', models.CharField(max_length=13, unique=True, verbose_name='spare code')),
                ('name', models.CharField(max_length=150, verbose_name='spare name')),
                ('unit_cost', models.FloatField(default=0.0, max_length=10, verbose_name='unit cost')),
            ],
            options={
                'verbose_name': 'Spares',
                'verbose_name_plural': 'Spares',
                'ordering': ['id'],
            },
        ),
    ]
