# Generated by Django 3.1.4 on 2021-01-06 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Engineering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payroll_number', models.CharField(max_length=15, unique=True)),
                ('full_name', models.CharField(max_length=50)),
                ('screen_name', models.CharField(max_length=25)),
                ('field', models.CharField(max_length=20)),
                ('phone_number', models.IntegerField(unique=True)),
                ('alternative_phone_number', models.IntegerField(blank=True, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Engineering',
                'verbose_name_plural': 'Engineering',
            },
        ),
    ]
